-- asadmin start-domain
-- asadmin stop-domain
/*
    employeedb
    jdbc:postgresql://localhost:5432/employeedb
    username=guest
    password=guest
*/

CREATE ROLE guest WITH
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'guest';

GRANT postgres TO guest;

CREATE DATABASE employee
    WITH
    OWNER = guest
    ENCODING = 'UTF8';


CREATE SCHEMA IF NOT EXISTS dbo AUTHORIZATION guest;

-- Drop table

-- DROP TABLE dbo.employee;

CREATE TABLE dbo.employee (
                              employee_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              date_of_birth date NOT NULL,
                              department_id int4 NOT NULL,
                              first_name text NOT NULL,
                              gender int4 NOT NULL,
                              job_title text NOT NULL,
                              last_name text NOT NULL,
                              CONSTRAINT employee_pkey PRIMARY KEY (employee_id)
);

